const messages: string[] = [];

messages[100] = "Continue"
messages[101] = "Switching Protocols"
messages[102] = "Processing"
messages[103] = "Early Hints"
messages[200] = "OK"
messages[201] = "Created"
messages[202] = "Accepted"
messages[203] = "Non-Authoritative Information"
messages[204] = "No Content"
messages[205] = "Reset Content"
messages[206] = "Partial Content"
messages[207] = "Multi-Status"
messages[208] = "Already Reported"
messages[226] = "IM Used"
messages[300] = "Multiple Choices"
messages[301] = "Moved Permanently"
messages[302] = "Found"
messages[303] = "See Other"
messages[304] = "Not Modified"
messages[307] = "Temporary Redirect"
messages[308] = "Permanent Redirect"
messages[400] = "Bad Request"
messages[401] = "Unauthorized"
messages[402] = "Payment Required"
messages[403] = "Forbidden"
messages[404] = "Not Found"
messages[405] = "Method Not Allowed"
messages[406] = "Not Acceptable"
messages[407] = "Proxy Authentication Required"
messages[408] = "Request Timeout"
messages[409] = "Conflict"
messages[410] = "Gone"
messages[411] = "Length Required"
messages[412] = "Precondition Failed"
messages[413] = "Content Too Large"
messages[414] = "URI Too Long"
messages[415] = "Unsupported Media Type"
messages[416] = "Range Not Satisfiable"
messages[417] = "Expectation Failed"
messages[418] = "I'm a teapot"
messages[421] = "Misdirected Request"
messages[422] = "Unprocessable Content"
messages[423] = "Locked"
messages[424] = "Failed Dependency"
messages[425] = "Too Early"
messages[426] = "Upgrade Required"
messages[428] = "Precondition Required"
messages[429] = "Too Many Requests"
messages[431] = "Request Header Fields Too Large"
messages[451] = "Unavailable For Legal Reasons"
messages[500] = "Internal Server Error"
messages[501] = "Not Implemented"
messages[502] = "Bad Gateway"
messages[503] = "Service Unavailable"
messages[504] = "Gateway Timeout"
messages[505] = "HTTP Version Not Supported"
messages[506] = "Variant Also Negotiates"
messages[507] = "Insufficient Storage"
messages[508] = "Loop Detected"
messages[510] = "Not Extended"
messages[511] = "Network Authentication Required"

export const HTTP_RESPONSE_STATUS = messages;

export enum HTTPStatusCodes {
    Continue = 100,
    SwitchingProtocols = 101,
    Processing = 102,
    EarlyHints = 103,
    OK = 200,
    Created = 201,
    Accepted = 202,
    NonAuthoritativeInformation = 203,
    NoContent = 204,
    ResetContent = 205,
    PartialContent = 206,
    MultiStatus = 207,
    AlreadyReported = 208,
    IMUsed = 226,
    MultipleChoices = 300,
    MovedPermanently = 301,
    Found = 302,
    SeeOther = 303,
    NotModified = 304,
    TemporaryRedirect = 307,
    PermanentRedirect = 308,
    BadRequest = 400,
    Unauthorized = 401,
    PaymentRequired = 402,
    Forbidden = 403,
    NotFound = 404,
    MethodNotAllowed = 405,
    NotAcceptable = 406,
    ProxyAuthenticationRequired = 407,
    RequestTimeout = 408,
    Conflict = 409,
    Gone = 410,
    LengthRequired = 411,
    PreconditionFailed = 412,
    ContentTooLarge = 413,
    URITooLong = 414,
    UnsupportedMediaType = 415,
    RangeNotSatisfiable = 416,
    ExpectationFailed = 417,
    ImATeapot = 418,
    MisdirectedRequest = 421,
    UnprocessableContent = 422,
    Locked = 423,
    FailedDependency = 424,
    TooEarly = 425,
    UpgradeRequired = 426,
    PreconditionRequired = 428,
    TooManyRequests = 429,
    RequestHeaderFieldsTooLarge = 431,
    UnavailableForLegalReasons = 451,
    InternalServerError = 500,
    NotImplemented = 501,
    BadGateway = 502,
    ServiceUnavailable = 503,
    GatewayTimeout = 504,
    HTTPVersionNotSupported = 505,
    VariantAlsoNegotiates = 506,
    InsufficientStorage = 507,
    LoopDetected = 508,
    NotExtended = 510,
    NetworkAuthenticationRequired = 511,
}
